import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { Crosshair, Flame, Route, Search, ShieldAlert, Trash2, XCircle } from 'lucide-react'

const sightings = route => (route?.features || []).filter(feature => feature.geometry?.type === 'Point').sort((a,b)=>new Date(a.properties.timestamp)-new Date(b.properties.timestamp))
export default function LeftDrawer({ tab, route, tracePlate, onTracePlateChange, heatNodes, corridors, blacklist, onTrace, onStopTracking, onAdd, onDelete, loading }) {
  const [blacklistPlate, setBlacklistPlate] = useState(''); const [reason, setReason] = useState('Stolen'); const entries = useMemo(()=>sightings(route),[route]); const target = route?.properties?.target_plate
  return <motion.aside key={tab} className="left-drawer h-[calc(100vh-2rem)] overflow-y-auto pb-24 flex flex-col custom-scrollbar" initial={{x:-36,opacity:0}} animate={{x:0,opacity:1}} exit={{x:-36,opacity:0}} transition={{type:'spring',stiffness:230,damping:27}}>
   {tab==='trace'&&<><div className="drawer-heading"><Route/> TRAJECTORY TRACE</div><form className="plate-search" onSubmit={event=>{event.preventDefault();onTrace(tracePlate)}}><Search size={16}/><input aria-label="Vehicle plate" value={tracePlate} onChange={event=>onTracePlateChange(event.target.value.toUpperCase())} placeholder="TN09AB1234"/><button className="trace-button"><Crosshair size={13}/>TRACE</button><button type="button" className="clear-trace" aria-label="Stop tracking" onClick={onStopTracking}><XCircle size={16}/></button></form>{loading&&<div className="drawer-note">RECONSTRUCTING TELEMETRY…</div>}{route&&<div className="route-summary"><span>TARGET</span><b>{target}</b><small>{route.properties?.total_sightings ?? entries.length} corroborated sightings</small></div>}<div className="sighting-timeline flex-1 overflow-y-auto pr-2 custom-scrollbar">{entries.map((feature,index)=>{const event=feature.properties;const recovered=event.detected_plate!==target;return <motion.article initial={{opacity:0,x:-14}} animate={{opacity:1,x:0}} transition={{delay:index*.08}} key={event.event_id} className={`sighting-card ${recovered?'recovered':''}`}><i>{String(index+1).padStart(2,'0')}</i><div><b>{event.camera_name}</b><small>{new Date(event.timestamp).toLocaleString('en-IN')}</small><strong>{event.detected_plate}</strong></div><span>{Math.round(event.ocr_confidence*100)}%</span></motion.article>})}{!loading&&!entries.length&&<div className="drawer-empty">ENTER A PLATE TO RECONSTRUCT ITS PATH</div>}</div></>}
   {tab==='heat'&&<><div className="drawer-heading"><Flame/> MACRO HEATMAP</div><p className="drawer-intro">Live congestion rank and origin-destination corridor intelligence.</p><h4>CONGESTED INTERSECTIONS</h4><div className="rank-list custom-scrollbar">{heatNodes.slice().sort((a,b)=>b.vehicles_per_minute-a.vehicles_per_minute).map((node,index)=><article key={node.camera_id}><i>0{index+1}</i><div><b>{node.name}</b><small>{node.camera_id} · {node.congestion_intensity}</small></div><strong>{node.vehicles_per_minute}<small>/min</small></strong></article>)}</div><h4>TOP CORRIDORS</h4><div className="corridor-list custom-scrollbar">{corridors.map(c=><article key={`${c.origin_name}-${c.destination_name}`}><span>{c.origin_name} <b>→</b> {c.destination_name}</span><small>{c.total_trips} trips · {c.avg_duration_minutes} min avg</small></article>)}</div></>}
   {tab==='watch'&&<><div className="drawer-heading"><ShieldAlert/> WATCHLIST MANAGER</div><form className="blacklist-form" onSubmit={event=>{event.preventDefault();onAdd({plate_text:blacklistPlate,reason,alert_priority:'CRITICAL'});setBlacklistPlate('')}}><input aria-label="Blacklist plate" value={blacklistPlate} onChange={event=>setBlacklistPlate(event.target.value.toUpperCase())} placeholder="REGISTRATION"/><select value={reason} onChange={event=>setReason(event.target.value)}><option>Stolen</option><option>Wanted</option><option>Investigation</option></select><button>ADD TO WATCHLIST</button></form><div className="watch-entries custom-scrollbar">{blacklist.map(item=><article key={item.plate_text}><ShieldAlert size={15}/><div><b>{item.plate_text}</b><small>{item.reason} · {item.alert_priority}</small></div><button onClick={()=>onDelete(item.plate_text)} aria-label={`Delete ${item.plate_text}`}><Trash2 size={15}/></button></article>)}{!blacklist.length&&<div className="drawer-empty">NO ACTIVE WATCHLIST ENTRIES</div>}</div></>}
  </motion.aside>
}
